app:
  client:
    baseUrl: http://localhost:4200

spring:
  data:
    redis:
      host: ${REDIS:localhost}
      port: 6379
  cache:
    redis:
      time-to-live: 1800000ms
  application:
    name: identity-service
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/identitydb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring:
          json:
            type:
              mapping: verification:com.example.identityservice.event.VerificationEvent, forgotpassword:com.example.identityservice.event.ForgotPasswordEvent
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: verificationTopic


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0