logging:
  level:
    org:
      springframework: ERROR
server:
  port: 8081
spring:
  application:
    name: product-query-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/productquerydb
    username: root
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.backend.dto
  data:
    redis:
      host: ${REDIS:localhost}
      port: 6379
  cache:
    redis:
      time-to-live: 1800000ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka