logging:
  level:
    org:
      springframework: ERROR
server:
  port: 8080
spring:
  application:
    name: product-command-service
  datasource:
    password: 123456789
    url: jdbc:postgresql://localhost:5432/product-command-db
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: ${REDIS:localhost}
      port: 6379
  cache:
    redis:
      time-to-live: 1800000ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka